# Generated by Django 5.2 on 2025-04-22 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routepoint",
            name="owner",
        ),
    ]
