# Generated by Django 5.2 on 2025-04-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0002_remove_routepoint_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="name",
            field=models.CharField(default="My first Route", max_length=20),
            preserve_default=False,
        ),
    ]
