# Generated by Django 5.2 on 2025-05-25 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0005_gameboard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="background",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="routes",
                to="routes.gameboard",
            ),
        ),
    ]
